import { Button, Input, ListItem, UnorderedList } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { createTask, deleteTask } from "./api/db/Polybase";
import { usePolybase, useCollection } from "@polybase/react";

export default function Home() {
  const polybase = usePolybase();
  const { data } = useCollection(polybase.collection("test-app/Tasks"));
  console.log(data?.data);
  const [tasks, setTasks] = useState([]);
  const [item, setItem] = useState("");

  useEffect(() => {
    if (data) {
      setTasks(data.data);
    }
  }, [data]);

  console.log(tasks);
  const onRemoveHandler = id => {
    deleteTask(id);
  };

  const onAddHandler = () => {
    createTask(Date.now().toString(), item);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UnorderedList className={styles.main}>
        <Input
          placeholder="write to do"
          className={styles.input}
          width="300px"
          value={item}
          onChange={e => setItem(e.target.value)}
        />
        <Button marginTop="20px" width="150px" onClick={onAddHandler}>
          Add item
        </Button>
        {tasks.map(task => (
          <ListItem key={task.data.id} className={styles.item}>
            {task.data.task}
            <Button ml={10} onClick={() => onRemoveHandler(task.data.id)}>
              X
            </Button>
          </ListItem>
        ))}
      </UnorderedList>
    </div>
  );
}
